//Global
export const GLOBAL_QUERY_LOCATION = 'GLOBAL_QUERY_LOCATION';
export const GLOBAL_QUERY_SHOP_LIST = 'GLOBAL_QUERY_SHOP_LIST';
export const SOCKET_INIT_SOCKET = 'SOCKET_INIT_SOCKET';
//auth
export const AUTHENTICATION_LOGIN = 'AUTHENTICATION_LOGIN';
export const AUTHENTICATION_REGISTER = 'AUTHENTICATION_REGISTER';
export const AUTHENTICATION_LOG_OUT = 'AUTHENTICATION_LOG_OUT';
export const AUTHENTICATION_CHANGE_PASSWORD = 'AUTHENTICATION_CHANGE_PASSWORD';
export const USER_UPDATE_INFO_USER = 'USER_UPDATE_INFO_USER';
export const USER_QUERY_SHOP_INFO = 'USER_QUERY_SHOP_INFO';
export const USER_UPDATE_ORDER_SHOP_INFO = 'USER_UPDATE_ORDER_SHOP_INFO';

//Food
export const FOOD_QUERY_FOOD_LIST = 'FOOD_QUERY_FOOD_LIST';
export const FOOD_QUERY_FOOD_DETAIL = 'FOOD_QUERY_FOOD_DETAIL';
export const FOOD_CREATE_FOOD = 'FOOD_CREATE_FOOD';
export const FOOD_UPDATE_FOOD = 'FOOD_UPDATE_FOOD';
export const FOOD_DELETE_FOOD_MANAGE = 'FOOD_DELETE_FOOD_MANAGE';
export const FOOD_QUERY_FOOD_TYPE = 'FOOD_QUERY_FOOD_TYPE';
export const FOOD_CHANGE_FOOD_STATUS = 'FOOD_CHANGE_FOOD_STATUS';
export const FOOD_QUERY_FOOD_LIST_CATEGORY = 'FOOD_QUERY_FOOD_LIST_CATEGORY';
export const QUERY_FOOD_NAME_SEARCH = 'QUERY_FOOD_NAME_SEARCH';

//Menu
export const MENU_QUERY_MENU_SHOP = 'MENU_QUERY_MENU_SHOP';
export const MENU_CREATE_MENU_SHOP = 'MENU_CREATE_MENU_SHOP';
export const MENU_UPDATE_MENU_SHOP = 'MENU_UPDATE_MENU_SHOP';
export const MENU_DELETE_MENU_SHOP = 'MENU_DELETE_MENU_SHOP';
export const MENU_QUERY_FOOD_IN_MENU = 'MENU_QUERY_FOOD_IN_MENU';
export const MENU_INSERT_FOOD_MENU_SHOP = 'MENU_INSERT_FOOD_MENU_SHOP';
export const MENU_DELETE_FOOD_MENU_SHOP = 'MENU_DELETE_FOOD_MENU_SHOP';

//Sale
export const SALE_CREATE_SALE_CODE = 'SALE_CREATE_SALE_CODE';
export const SALE_QUERY_SALE_CODE_LIST = 'SALE_QUERY_SALE_CODE_LIST';
export const SALE_QUERY_SALE_TYPE = 'SALE_QUERY_SALE_TYPE';

//common
export const COMMON_SHOW_NOTIFICATION = 'COMMON_SHOW_NOTIFICATION';

//Order
export const ORDER_QUERY_ORDER = 'ORDER_QUERY_ORDER';
export const ORDER_UPDATE_ORDER = 'ORDER_UPDATE_ORDER';
export const STATISTICAL_QUERY_ORDER_SHOP = 'STATISTICAL_QUERY_ORDER_SHOP';
export const ORDER_QUERY_ORDER_STATUS = 'ORDER_QUERY_ORDER_STATUS';

//Shop
export const USER_QUERY_SHOP_TYPE = 'USER_QUERY_SHOP_TYPE';
export const ORDER_QUERY_ORDER_DETAIL = 'ORDER_QUERY_ORDER_DETAIL';
export const QUERY_RESTAURANT_NAME = 'QUERY_RESTAURANT_NAME';

//Customer
export const QUERY_COMMENT = 'QUERY_COMMENT';
export const REQUEST_COMMENT = 'REQUEST_COMMENT';
export const REQUEST_RATING = 'REQUEST_RATING';
export const QUERY_RATING = 'QUERY_RATING';
export const ORDER_FOOD = 'ORDER_FOOD';
export const DELETE_FOOD = 'DELETE_FOOD';
export const USER_QUERY_CUS_INFO = 'USER_QUERY_CUS_INFO';
export const USER_UPDATE_INFO_CUS = 'USER_UPDATE_INFO_CUS';
export const FOOD_QUERY_FAVORITE_FOOD_LIST = 'FOOD_QUERY_FAVORITE_FOOD_LIST';
export const FOOD_DELETE_FAVORITE_FOOD_LIST = 'FOOD_DELETE_FAVORITE_FOOD_LIST';

//rating
export const USER_QUERY_RATING_LIST = 'USER_QUERY_RATING_LIST';

//admin
export const ADMIN_QUERY_SHOP_PENDING_LIST = 'ADMIN_QUERY_SHOP_PENDING_LIST';
export const ADMIN_DECISION_SHOP_REGISTER = 'ADMIN_DECISION_SHOP_REGISTER';
export const ADMIN_QUERY_ADMIN_INFO = 'ADMIN_QUERY_ADMIN_INFO';
export const QUERY_CUS_LIST = 'QUERY_CUS_LIST';
export const ADMIN_DELETE_CUS = 'ADMIN_DELETE_CUS';
export const AUTHENTICATION_LOGIN_ADMIN = 'AUTHENTICATION_LOGIN_ADMIN';

// history
export const QUERY_HISTORY = 'QUERY_HISTORY';

export const PLACE_ORDER = 'PLACE_ORDER';

export const CHATBOT_ADD_NEW_USER_MESSAGE = 'CHATBOT_ADD_NEW_USER_MESSAGE';
export const CHATBOT_ADD_USER_MESSAGE = 'CHATBOT_ADD_USER_MESSAGE';
export const SHOP_QUERY_SHOP_LIST_CATEGORY = 'SHOP_QUERY_SHOP_LIST_CATEGORY';
export const QUERY_LIST_CATEGORY = 'QUERY_LIST_CATEGORY';
export const QUERY_LIST_DISTRICT = 'QUERY_LIST_DISTRICT';
export const QUERY_INFO_ACCOUNT = 'QUERY_INFO_ACCOUNT';
